// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppArouse: typeof import('./../src/components/AppArouse.vue')['default']
    ContactButton: typeof import('./../src/components/ContactButton.vue')['default']
    FloatingPanel: typeof import('./../src/components/FloatingPanel.vue')['default']
    Guide: typeof import('./../src/components/Guide.vue')['default']
    Popups: typeof import('./../src/components/Popups.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/Search.vue')['default']
    Share: typeof import('./../src/components/Share.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanImage: typeof import('vant/es')['Image']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
